### ISSUE TITLE
[iperf3] bad json file

### ISSUE THREAD

**Issue by okibcn** [x-magic/scoop-bucket#1]
iperf3.json has a couple of issues:

1. It reports an incorrect version. 3.12 doesn't exists.
2. It doesn't have autoupdate.

The recommended json with integrated autoupdate is:
```json
{
    "version": "3.1.3",
    "description": "Tool for measuring the maximum achievable bandwidth on IP networks",
    "homepage": "https://iperf.fr/",
    "license": "BSD-3-Clause",
    "architecture": {
        "64bit": {
            "url": "https://iperf.fr/download/windows/iperf-3.1.3-win64.zip",
            "hash": "3c3db693c1bdcc902ca9198fc716339373658233b3392ffe3d467f7695762cd1",
            "extract_dir": "iperf-3.1.3-win64"
        },
        "32bit": {
            "url": "https://iperf.fr/download/windows/iperf-3.1.3-win32.zip",
            "hash": "b3f8e262c17a000a30bf4f2135dfed644587cf2ec649f878aea8e9de51ffc8f2",
            "extract_dir": "iperf-3.1.3-win32"
        }
    },
    "bin": "iperf3.exe",
    "checkver": {
        "url": "https://iperf.fr/iperf-download.php",
        "regex": "iPerf ([\\d.]+)<\\/a>"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://iperf.fr/download/windows/iperf-$version-win64.zip",
                "extract_dir": "iperf-$version-win64"
            },
            "32bit": {
                "url": "https://iperf.fr/download/windows/iperf-$version-win32.zip",
                "extract_dir": "iperf-$version-win32"
            }
        },
        "hash": {
            "url": "$baseurl/sha256sum.txt"
        }
    }
}
```

**Comment by x-magic** [comment]
This is not an offical bucket and the version collected here is a non-official build that is much more up to date than official. No auto updates in place on purpose. 

Read https://github.com/x-magic/scoop-bucket/blob/master/README.md first.

**Comment by okibcn** [comment]
Then probably you should change the name to iperf3mod, iperf3plus, or something as it is not the official one and could be misleading. I will try this version. Thanks

**Comment by x-magic** [comment]
> Then probably you should change the name to iperf3mod, iperf3plus, or something as it is not the official one and could be misleading. I will try this version. Thanks

There was no latest official Windows binary build for iperf3. And technically speaking the builds from `files.budman.pw` are binary compiled from unmodified source. 

Interestingly enough the official website now lists `files.budman.pw` in its binary downloads section alongside another build in a GitHub repo.
